/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2022-06-15 04:15:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.decorators;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/common/admin/menu.jsp", Long.valueOf(1655258536604L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1655234795149L));
    _jspx_dependants.put("/common/admin/footer.jsp", Long.valueOf(1655258651750L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1587378334766L));
    _jspx_dependants.put("/common/admin/header.jsp", Long.valueOf(1655258197542L));
    _jspx_dependants.put("jar:file:/D:/04.%20Projects/java-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/java-app/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1655227900242L));
    _jspx_dependants.put("jar:file:/D:/04.%20Projects/java-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/java-app/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdec_005fbody_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fdec_005fbody_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>");
      if (_jspx_meth_dec_005ftitle_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("<!-- bootstrap & fontawesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("<!-- text fonts -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("<!-- ace styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" class=\"ace-main-stylesheet\" id=\"main-ace-style\" />\r\n");
      out.write("<script src=\"/template/admin/js/ace-extra.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"no-skin\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t");
      out.write("<div id=\"navbar\" class=\"navbar navbar-default\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\ttry {\r\n");
      out.write("\t\t\tace.settings.check('navbar', 'fixed')\r\n");
      out.write("\t\t} catch (e) {\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"navbar-container\" id=\"navbar-container\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"navbar-toggle menu-toggler pull-left\"\r\n");
      out.write("\t\t\tid=\"menu-toggler\" data-target=\"#sidebar\">\r\n");
      out.write("\t\t\t<span class=\"sr-only\">Toggle sidebar</span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"navbar-header pull-left\">\r\n");
      out.write("\t\t\t<a href=\"index.html\" class=\"navbar-brand\"> <small> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-leaf\"></i> Ace Admin\r\n");
      out.write("\t\t\t</small>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"navbar-buttons navbar-header pull-right\" role=\"navigation\">\r\n");
      out.write("\t\t\t<ul class=\"nav ace-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"grey\"><a data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-toggle\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"ace-icon fa fa-tasks\"></i> <span class=\"badge badge-grey\">4</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul\r\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-header\"><i class=\"ace-icon fa fa-check\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t4 Tasks to complete</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-navbar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Software Update</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"pull-right\">65%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-mini\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width: 65%\" class=\"progress-bar\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Hardware Upgrade</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"pull-right\">35%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-mini\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width: 35%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"progress-bar progress-bar-danger\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Unit Testing</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"pull-right\">15%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-mini\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width: 15%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"progress-bar progress-bar-warning\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Bug Fixes</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"pull-right\">90%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-mini progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width: 90%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"progress-bar progress-bar-success\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-footer\"><a href=\"#\"> See tasks with\r\n");
      out.write("\t\t\t\t\t\t\t\tdetails <i class=\"ace-icon fa fa-arrow-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"purple\"><a data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-toggle\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"ace-icon fa fa-bell icon-animated-bell\"></i> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"badge badge-important\">8</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul\r\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-header\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"ace-icon fa fa-exclamation-triangle\"></i> 8 Notifications\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-navbar navbar-pink\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-xs no-hover btn-pink fa fa-comment\"></i> New\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tComments\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span> <span class=\"pull-right badge badge-info\">+12</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-xs btn-primary fa fa-user\"></i> Bob just signed\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tup as an editor ...\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-xs no-hover btn-success fa fa-shopping-cart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tNew Orders\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span> <span class=\"pull-right badge badge-success\">+8</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-xs no-hover btn-info fa fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tFollowers\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span> <span class=\"pull-right badge badge-info\">+11</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-footer\"><a href=\"#\"> See all\r\n");
      out.write("\t\t\t\t\t\t\t\tnotifications <i class=\"ace-icon fa fa-arrow-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"green\"><a data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-toggle\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"ace-icon fa fa-envelope icon-animated-vertical\"></i> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"badge badge-success\">5</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul\r\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-header\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"ace-icon fa fa-envelope-o\"></i> 5 Messages</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-navbar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"clearfix\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"assets/avatars/avatar.png\" class=\"msg-photo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Alex's Avatar\" /> <span class=\"msg-body\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"msg-title\"> <span class=\"blue\">Alex:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tCiao sociis natoque penatibus et auctor ...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span class=\"msg-time\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-clock-o\"></i> <span>a moment\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"clearfix\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"assets/avatars/avatar3.png\" class=\"msg-photo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Susan's Avatar\" /> <span class=\"msg-body\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"msg-title\"> <span class=\"blue\">Susan:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tVestibulum id ligula porta felis euismod ...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span class=\"msg-time\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-clock-o\"></i> <span>20 minutes\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"clearfix\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"assets/avatars/avatar4.png\" class=\"msg-photo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Bob's Avatar\" /> <span class=\"msg-body\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"msg-title\"> <span class=\"blue\">Bob:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tNullam quis risus eget urna mollis ornare ...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span class=\"msg-time\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-clock-o\"></i> <span>3:15 pm</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"clearfix\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"assets/avatars/avatar2.png\" class=\"msg-photo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Kate's Avatar\" /> <span class=\"msg-body\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"msg-title\"> <span class=\"blue\">Kate:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tCiao sociis natoque eget urna mollis ornare ...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span class=\"msg-time\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-clock-o\"></i> <span>1:33 pm</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"clearfix\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"assets/avatars/avatar5.png\" class=\"msg-photo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Fred's Avatar\" /> <span class=\"msg-body\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"msg-title\"> <span class=\"blue\">Fred:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tVestibulum id penatibus et auctor ...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span class=\"msg-time\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-clock-o\"></i> <span>10:09 am</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-footer\"><a href=\"inbox.html\"> See all\r\n");
      out.write("\t\t\t\t\t\t\t\tmessages <i class=\"ace-icon fa fa-arrow-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"light-blue\"><a data-toggle=\"dropdown\" href=\"#\"\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-toggle\"> <img class=\"nav-user-photo\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"assets/avatars/user.jpg\" alt=\"Jason's Photo\" /> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"user-info\"> <small>Welcome,</small> Jason\r\n");
      out.write("\t\t\t\t\t</span> <i class=\"ace-icon fa fa-caret-down\"></i>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul\r\n");
      out.write("\t\t\t\t\t\tclass=\"user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"ace-icon fa fa-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\tSettings\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"profile.html\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-user\"></i> Profile\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"ace-icon fa fa-power-off\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\tLogout\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.navbar-container -->\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Contain -->\r\n");
      out.write("\t<div class=\"main-container\" id=\"main-container\">\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\ttry{ace.settings.check('main-container' , 'fixed')}catch(e){}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!-- Menu -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div id=\"sidebar\" class=\"sidebar                  responsive\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\ttry {\r\n");
      out.write("\t\t\tace.settings.check('sidebar', 'fixed')\r\n");
      out.write("\t\t} catch (e) {\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"sidebar-shortcuts\" id=\"sidebar-shortcuts\">\r\n");
      out.write("\t\t<div class=\"sidebar-shortcuts-large\" id=\"sidebar-shortcuts-large\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-success\">\r\n");
      out.write("\t\t\t\t<i class=\"ace-icon fa fa-signal\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"btn btn-info\">\r\n");
      out.write("\t\t\t\t<i class=\"ace-icon fa fa-pencil\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"btn btn-warning\">\r\n");
      out.write("\t\t\t\t<i class=\"ace-icon fa fa-users\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"btn btn-danger\">\r\n");
      out.write("\t\t\t\t<i class=\"ace-icon fa fa-cogs\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"sidebar-shortcuts-mini\" id=\"sidebar-shortcuts-mini\">\r\n");
      out.write("\t\t\t<span class=\"btn btn-success\"></span> <span class=\"btn btn-info\"></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<span class=\"btn btn-warning\"></span> <span class=\"btn btn-danger\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.sidebar-shortcuts -->\r\n");
      out.write("\r\n");
      out.write("\t<ul class=\"nav nav-list\">\r\n");
      out.write("\t\t<li class=\"active\"><a href=\"index.html\"> <i\r\n");
      out.write("\t\t\t\tclass=\"menu-icon fa fa-tachometer\"></i> <span class=\"menu-text\">\r\n");
      out.write("\t\t\t\t\tDashboard </span>\r\n");
      out.write("\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"\"><a href=\"#\" class=\"dropdown-toggle\"> <i\r\n");
      out.write("\t\t\t\tclass=\"menu-icon fa fa-desktop\"></i> <span class=\"menu-text\">\r\n");
      out.write("\t\t\t\t\tUI &amp; Elements </span> <b class=\"arrow fa fa-angle-down\"></b>\r\n");
      out.write("\t\t</a> <b class=\"arrow\"></b>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"submenu\">\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"#\" class=\"dropdown-toggle\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Layouts <b\r\n");
      out.write("\t\t\t\t\t\tclass=\"arrow fa fa-angle-down\"></b>\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"submenu\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"\"><a href=\"top-menu.html\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Top Menu\r\n");
      out.write("\t\t\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"\"><a href=\"two-menu-1.html\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Two Menus 1\r\n");
      out.write("\t\t\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"\"><a href=\"two-menu-2.html\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Two Menus 2\r\n");
      out.write("\t\t\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"\"><a href=\"mobile-menu-1.html\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Default Mobile Menu\r\n");
      out.write("\t\t\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"\"><a href=\"mobile-menu-2.html\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Mobile Menu 2\r\n");
      out.write("\t\t\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"\"><a href=\"mobile-menu-3.html\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Mobile Menu 3\r\n");
      out.write("\t\t\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"typography.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Typography\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"elements.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Elements\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"buttons.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Buttons &amp; Icons\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"content-slider.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Content Sliders\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"treeview.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Treeview\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"jquery-ui.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> jQuery UI\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"nestable-list.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Nestable Lists\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"#\" class=\"dropdown-toggle\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Three Level Menu <b\r\n");
      out.write("\t\t\t\t\t\tclass=\"arrow fa fa-angle-down\"></b>\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"submenu\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"\"><a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu-icon fa fa-leaf green\"></i> Item #1\r\n");
      out.write("\t\t\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"\"><a href=\"#\" class=\"dropdown-toggle\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu-icon fa fa-pencil orange\"></i> 4th level <b\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"arrow fa fa-angle-down\"></b>\r\n");
      out.write("\t\t\t\t\t\t</a> <b class=\"arrow\"></b>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"submenu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"\"><a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"menu-icon fa fa-plus purple\"></i> Add Product\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"\"><a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"menu-icon fa fa-eye pink\"></i> View Products\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"\"><a href=\"#\" class=\"dropdown-toggle\"> <i\r\n");
      out.write("\t\t\t\tclass=\"menu-icon fa fa-list\"></i> <span class=\"menu-text\">\r\n");
      out.write("\t\t\t\t\tTables </span> <b class=\"arrow fa fa-angle-down\"></b>\r\n");
      out.write("\t\t</a> <b class=\"arrow\"></b>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"submenu\">\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"tables.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Simple &amp; Dynamic\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"jqgrid.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> jqGrid plugin\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"\"><a href=\"#\" class=\"dropdown-toggle\"> <i\r\n");
      out.write("\t\t\t\tclass=\"menu-icon fa fa-pencil-square-o\"></i> <span class=\"menu-text\">\r\n");
      out.write("\t\t\t\t\tForms </span> <b class=\"arrow fa fa-angle-down\"></b>\r\n");
      out.write("\t\t</a> <b class=\"arrow\"></b>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"submenu\">\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"form-elements.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Form Elements\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"form-elements-2.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Form Elements 2\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"form-wizard.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Wizard &amp; Validation\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"wysiwyg.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Wysiwyg &amp; Markdown\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"dropzone.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Dropzone File Upload\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"\"><a href=\"widgets.html\"> <i\r\n");
      out.write("\t\t\t\tclass=\"menu-icon fa fa-list-alt\"></i> <span class=\"menu-text\">\r\n");
      out.write("\t\t\t\t\tWidgets </span>\r\n");
      out.write("\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"\"><a href=\"calendar.html\"> <i\r\n");
      out.write("\t\t\t\tclass=\"menu-icon fa fa-calendar\"></i> <span class=\"menu-text\">\r\n");
      out.write("\t\t\t\t\tCalendar <span class=\"badge badge-transparent tooltip-error\"\r\n");
      out.write("\t\t\t\t\ttitle=\"2 Important Events\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"ace-icon fa fa-exclamation-triangle red bigger-130\"></i>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"\"><a href=\"gallery.html\"> <i\r\n");
      out.write("\t\t\t\tclass=\"menu-icon fa fa-picture-o\"></i> <span class=\"menu-text\">\r\n");
      out.write("\t\t\t\t\tGallery </span>\r\n");
      out.write("\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"\"><a href=\"#\" class=\"dropdown-toggle\"> <i\r\n");
      out.write("\t\t\t\tclass=\"menu-icon fa fa-tag\"></i> <span class=\"menu-text\">\r\n");
      out.write("\t\t\t\t\tMore Pages </span> <b class=\"arrow fa fa-angle-down\"></b>\r\n");
      out.write("\t\t</a> <b class=\"arrow\"></b>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"submenu\">\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"profile.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> User Profile\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"inbox.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Inbox\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"pricing.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Pricing Tables\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"invoice.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Invoice\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"timeline.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Timeline\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"email.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Email Templates\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"login.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Login &amp; Register\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"\"><a href=\"#\" class=\"dropdown-toggle\"> <i\r\n");
      out.write("\t\t\t\tclass=\"menu-icon fa fa-file-o\"></i> <span class=\"menu-text\">\r\n");
      out.write("\t\t\t\t\tOther Pages <span class=\"badge badge-primary\">5</span>\r\n");
      out.write("\t\t\t</span> <b class=\"arrow fa fa-angle-down\"></b>\r\n");
      out.write("\t\t</a> <b class=\"arrow\"></b>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"submenu\">\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"faq.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> FAQ\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"error-404.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Error 404\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"error-500.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Error 500\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"grid.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Grid\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"blank.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon fa fa-caret-right\"></i> Blank Page\r\n");
      out.write("\t\t\t\t</a> <b class=\"arrow\"></b></li>\r\n");
      out.write("\t\t\t</ul></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<!-- /.nav-list -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"sidebar-toggle sidebar-collapse\" id=\"sidebar-collapse\">\r\n");
      out.write("\t\t<i class=\"ace-icon fa fa-angle-double-left\"\r\n");
      out.write("\t\t\tdata-icon1=\"ace-icon fa fa-angle-double-left\"\r\n");
      out.write("\t\t\tdata-icon2=\"ace-icon fa fa-angle-double-right\"></i>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\ttry {\r\n");
      out.write("\t\t\tace.settings.check('sidebar', 'collapsed')\r\n");
      out.write("\t\t} catch (e) {\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t<!-- Menu -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_dec_005fbody_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<div class=\"footer-inner\">\r\n");
      out.write("\t\t<div class=\"footer-content\">\r\n");
      out.write("\t\t\t<span class=\"bigger-120\"> <span class=\"blue bolder\">Ace</span>\r\n");
      out.write("\t\t\t\tApplication &copy; 2013-2014\r\n");
      out.write("\t\t\t</span> &nbsp; &nbsp; <span class=\"action-buttons\"> <a href=\"#\">\r\n");
      out.write("\t\t\t\t\t<i class=\"ace-icon fa fa-twitter-square light-blue bigger-150\"></i>\r\n");
      out.write("\t\t\t</a> <a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"ace-icon fa fa-facebook-square text-primary bigger-150\"></i>\r\n");
      out.write("\t\t\t</a> <a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"ace-icon fa fa-rss-square orange bigger-150\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a href=\"#\" id=\"btn-scroll-up\" class=\"btn-scroll-up btn btn-sm btn-inverse\">\r\n");
      out.write("\t\t\t\t<i class=\"ace-icon fa fa-angle-double-up icon-only bigger-110\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Menu -->\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"js/jquery.2.1.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.jQuery\r\n");
      out.write("\t\t\t\t|| document.write(\"<script src='assets/js/jquery.min.js'>\"\r\n");
      out.write("\t\t\t\t\t\t+ \"<\"+\"/script>\");\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tif ('ontouchstart' in document.documentElement)\r\n");
      out.write("\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t.write(\"<script src='assets/js/jquery.mobile.custom.min.js'>\"\r\n");
      out.write("\t\t\t\t\t\t\t+ \"<\"+\"/script>\");\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"template/admin/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"template/admin/js/jquery-ui.custom.min.js\"></script>\r\n");
      out.write("\t<script src=\"template/admin/js/jquery.ui.touch-punch.min.js\"></script>\r\n");
      out.write("\t<script src=\"template/admin/js/jquery.easypiechart.min.js\"></script>\r\n");
      out.write("\t<script src=\"template/admin/js/jquery.sparkline.min.js\"></script>\r\n");
      out.write("\t<script src=\"template/admin/js/jquery.flot.min.js\"></script>\r\n");
      out.write("\t<script src=\"template/admin/js/jquery.flot.pie.min.js\"></script>\r\n");
      out.write("\t<script src=\"template/admin/js/jquery.flot.resize.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ace scripts -->\r\n");
      out.write("\t<script src=\"template/admin/js/ace-elements.min.js\"></script>\r\n");
      out.write("\t<script src=\"template/admin/js/ace.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- inline scripts related to this page -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tjQuery(function($) {\r\n");
      out.write("\t\t\t$('.easy-pie-chart.percentage')\r\n");
      out.write("\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar $box = $(this).closest('.infobox');\r\n");
      out.write("\t\t\t\t\t\t\t\tvar barColor = $(this).data('color')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t|| (!$box.hasClass('infobox-dark') ? $box\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.css('color')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t: 'rgba(255,255,255,0.95)');\r\n");
      out.write("\t\t\t\t\t\t\t\tvar trackColor = barColor == 'rgba(255,255,255,0.95)' ? 'rgba(255,255,255,0.25)'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t: '#E2E2E2';\r\n");
      out.write("\t\t\t\t\t\t\t\tvar size = parseInt($(this).data('size')) || 50;\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.easyPieChart(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tbarColor : barColor,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttrackColor : trackColor,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tscaleColor : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tlineCap : 'butt',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tlineWidth : parseInt(size / 10),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tanimate : /msie\\s*(8|7|6)/\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.test(navigator.userAgent\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.toLowerCase()) ? false\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t: 1000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tsize : size\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('.sparkline').each(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar $box = $(this).closest('.infobox');\r\n");
      out.write("\t\t\t\t\t\tvar barColor = !$box.hasClass('infobox-dark') ? $box\r\n");
      out.write("\t\t\t\t\t\t\t\t.css('color') : '#FFF';\r\n");
      out.write("\t\t\t\t\t\t$(this).sparkline('html', {\r\n");
      out.write("\t\t\t\t\t\t\ttagValuesAttribute : 'data-values',\r\n");
      out.write("\t\t\t\t\t\t\ttype : 'bar',\r\n");
      out.write("\t\t\t\t\t\t\tbarColor : barColor,\r\n");
      out.write("\t\t\t\t\t\t\tchartRangeMin : $(this).data('min') || 0\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t//flot chart resize plugin, somehow manipulates default browser resize event to optimize it!\r\n");
      out.write("\t\t\t//but sometimes it brings up errors with normal resize event handlers\r\n");
      out.write("\t\t\t$.resize.throttleWindow = false;\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar placeholder = $('#piechart-placeholder').css({\r\n");
      out.write("\t\t\t\t'width' : '90%',\r\n");
      out.write("\t\t\t\t'min-height' : '150px'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tvar data = [ {\r\n");
      out.write("\t\t\t\tlabel : \"social networks\",\r\n");
      out.write("\t\t\t\tdata : 38.7,\r\n");
      out.write("\t\t\t\tcolor : \"#68BC31\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tlabel : \"search engines\",\r\n");
      out.write("\t\t\t\tdata : 24.5,\r\n");
      out.write("\t\t\t\tcolor : \"#2091CF\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tlabel : \"ad campaigns\",\r\n");
      out.write("\t\t\t\tdata : 8.2,\r\n");
      out.write("\t\t\t\tcolor : \"#AF4E96\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tlabel : \"direct traffic\",\r\n");
      out.write("\t\t\t\tdata : 18.6,\r\n");
      out.write("\t\t\t\tcolor : \"#DA5430\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tlabel : \"other\",\r\n");
      out.write("\t\t\t\tdata : 10,\r\n");
      out.write("\t\t\t\tcolor : \"#FEE074\"\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t\tfunction drawPieChart(placeholder, data, position) {\r\n");
      out.write("\t\t\t\t$.plot(placeholder, data, {\r\n");
      out.write("\t\t\t\t\tseries : {\r\n");
      out.write("\t\t\t\t\t\tpie : {\r\n");
      out.write("\t\t\t\t\t\t\tshow : true,\r\n");
      out.write("\t\t\t\t\t\t\ttilt : 0.8,\r\n");
      out.write("\t\t\t\t\t\t\thighlight : {\r\n");
      out.write("\t\t\t\t\t\t\t\topacity : 0.25\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tstroke : {\r\n");
      out.write("\t\t\t\t\t\t\t\tcolor : '#fff',\r\n");
      out.write("\t\t\t\t\t\t\t\twidth : 2\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tstartAngle : 2\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tlegend : {\r\n");
      out.write("\t\t\t\t\t\tshow : true,\r\n");
      out.write("\t\t\t\t\t\tposition : position || \"ne\",\r\n");
      out.write("\t\t\t\t\t\tlabelBoxBorderColor : null,\r\n");
      out.write("\t\t\t\t\t\tmargin : [ -30, 15 ]\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tgrid : {\r\n");
      out.write("\t\t\t\t\t\thoverable : true,\r\n");
      out.write("\t\t\t\t\t\tclickable : true\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdrawPieChart(placeholder, data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t/**\r\n");
      out.write("\t\t\twe saved the drawing function and the data to redraw with different position later when switching to RTL mode dynamically\r\n");
      out.write("\t\t\tso that's not needed actually.\r\n");
      out.write("\t\t\t */\r\n");
      out.write("\t\t\tplaceholder.data('chart', data);\r\n");
      out.write("\t\t\tplaceholder.data('draw', drawPieChart);\r\n");
      out.write("\r\n");
      out.write("\t\t\t//pie chart tooltip example\r\n");
      out.write("\t\t\tvar $tooltip = $(\r\n");
      out.write("\t\t\t\t\t\"<div class='tooltip top in'><div class='tooltip-inner'></div></div>\")\r\n");
      out.write("\t\t\t\t\t.hide().appendTo('body');\r\n");
      out.write("\t\t\tvar previousPoint = null;\r\n");
      out.write("\r\n");
      out.write("\t\t\tplaceholder.on('plothover', function(event, pos, item) {\r\n");
      out.write("\t\t\t\tif (item) {\r\n");
      out.write("\t\t\t\t\tif (previousPoint != item.seriesIndex) {\r\n");
      out.write("\t\t\t\t\t\tpreviousPoint = item.seriesIndex;\r\n");
      out.write("\t\t\t\t\t\tvar tip = item.series['label'] + \" : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ item.series['percent'] + '%';\r\n");
      out.write("\t\t\t\t\t\t$tooltip.show().children(0).text(tip);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$tooltip.css({\r\n");
      out.write("\t\t\t\t\t\ttop : pos.pageY + 10,\r\n");
      out.write("\t\t\t\t\t\tleft : pos.pageX + 10\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$tooltip.hide();\r\n");
      out.write("\t\t\t\t\tpreviousPoint = null;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t/////////////////////////////////////\r\n");
      out.write("\t\t\t$(document).one('ajaxloadstart.page', function(e) {\r\n");
      out.write("\t\t\t\t$tooltip.remove();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar d1 = [];\r\n");
      out.write("\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.5) {\r\n");
      out.write("\t\t\t\td1.push([ i, Math.sin(i) ]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar d2 = [];\r\n");
      out.write("\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.5) {\r\n");
      out.write("\t\t\t\td2.push([ i, Math.cos(i) ]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar d3 = [];\r\n");
      out.write("\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.2) {\r\n");
      out.write("\t\t\t\td3.push([ i, Math.tan(i) ]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar sales_charts = $('#sales-charts').css({\r\n");
      out.write("\t\t\t\t'width' : '100%',\r\n");
      out.write("\t\t\t\t'height' : '220px'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$.plot(\"#sales-charts\", [ {\r\n");
      out.write("\t\t\t\tlabel : \"Domains\",\r\n");
      out.write("\t\t\t\tdata : d1\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tlabel : \"Hosting\",\r\n");
      out.write("\t\t\t\tdata : d2\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tlabel : \"Services\",\r\n");
      out.write("\t\t\t\tdata : d3\r\n");
      out.write("\t\t\t} ], {\r\n");
      out.write("\t\t\t\thoverable : true,\r\n");
      out.write("\t\t\t\tshadowSize : 0,\r\n");
      out.write("\t\t\t\tseries : {\r\n");
      out.write("\t\t\t\t\tlines : {\r\n");
      out.write("\t\t\t\t\t\tshow : true\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tpoints : {\r\n");
      out.write("\t\t\t\t\t\tshow : true\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\txaxis : {\r\n");
      out.write("\t\t\t\t\ttickLength : 0\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tyaxis : {\r\n");
      out.write("\t\t\t\t\tticks : 10,\r\n");
      out.write("\t\t\t\t\tmin : -2,\r\n");
      out.write("\t\t\t\t\tmax : 2,\r\n");
      out.write("\t\t\t\t\ttickDecimals : 3\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tgrid : {\r\n");
      out.write("\t\t\t\t\tbackgroundColor : {\r\n");
      out.write("\t\t\t\t\t\tcolors : [ \"#fff\", \"#fff\" ]\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tborderWidth : 1,\r\n");
      out.write("\t\t\t\t\tborderColor : '#555'\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('#recent-box [data-rel=\"tooltip\"]').tooltip({\r\n");
      out.write("\t\t\t\tplacement : tooltip_placement\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tfunction tooltip_placement(context, source) {\r\n");
      out.write("\t\t\t\tvar $source = $(source);\r\n");
      out.write("\t\t\t\tvar $parent = $source.closest('.tab-content')\r\n");
      out.write("\t\t\t\tvar off1 = $parent.offset();\r\n");
      out.write("\t\t\t\tvar w1 = $parent.width();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar off2 = $source.offset();\r\n");
      out.write("\t\t\t\t//var w2 = $source.width();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (parseInt(off2.left) < parseInt(off1.left)\r\n");
      out.write("\t\t\t\t\t\t+ parseInt(w1 / 2))\r\n");
      out.write("\t\t\t\t\treturn 'right';\r\n");
      out.write("\t\t\t\treturn 'left';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('.dialogs,.comments').ace_scroll({\r\n");
      out.write("\t\t\t\tsize : 300\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t//Android's default browser somehow is confused when tapping on label which will lead to dragging the task\r\n");
      out.write("\t\t\t//so disable dragging when clicking on label\r\n");
      out.write("\t\t\tvar agent = navigator.userAgent.toLowerCase();\r\n");
      out.write("\t\t\tif (\"ontouchstart\" in document && /applewebkit/.test(agent)\r\n");
      out.write("\t\t\t\t\t&& /android/.test(agent))\r\n");
      out.write("\t\t\t\t$('#tasks').on('touchstart', function(e) {\r\n");
      out.write("\t\t\t\t\tvar li = $(e.target).closest('#tasks li');\r\n");
      out.write("\t\t\t\t\tif (li.length == 0)\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\tvar label = li.find('label.inline').get(0);\r\n");
      out.write("\t\t\t\t\tif (label == e.target || $.contains(label, e.target))\r\n");
      out.write("\t\t\t\t\t\te.stopImmediatePropagation();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('#tasks').sortable({\r\n");
      out.write("\t\t\t\topacity : 0.8,\r\n");
      out.write("\t\t\t\trevert : true,\r\n");
      out.write("\t\t\t\tforceHelperSize : true,\r\n");
      out.write("\t\t\t\tplaceholder : 'draggable-placeholder',\r\n");
      out.write("\t\t\t\tforcePlaceholderSize : true,\r\n");
      out.write("\t\t\t\ttolerance : 'pointer',\r\n");
      out.write("\t\t\t\tstop : function(event, ui) {\r\n");
      out.write("\t\t\t\t\t//just for Chrome!!!! so that dropdowns on items don't appear below other items after being moved\r\n");
      out.write("\t\t\t\t\t$(ui.item).css('z-index', 'auto');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#tasks').disableSelection();\r\n");
      out.write("\t\t\t$('#tasks input:checkbox').removeAttr('checked').on('click',\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tif (this.checked)\r\n");
      out.write("\t\t\t\t\t\t\t$(this).closest('li').addClass('selected');\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$(this).closest('li').removeClass('selected');\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t//show the dropdowns on top or bottom depending on window height and menu position\r\n");
      out.write("\t\t\t$('#task-tab .dropdown-hover').on('mouseenter', function(e) {\r\n");
      out.write("\t\t\t\tvar offset = $(this).offset();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar $w = $(window)\r\n");
      out.write("\t\t\t\tif (offset.top > $w.scrollTop() + $w.innerHeight() - 100)\r\n");
      out.write("\t\t\t\t\t$(this).addClass('dropup');\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t$(this).removeClass('dropup');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_dec_005ftitle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dec:title
    com.opensymphony.module.sitemesh.taglib.decorator.TitleTag _jspx_th_dec_005ftitle_005f0 = (com.opensymphony.module.sitemesh.taglib.decorator.TitleTag) _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.get(com.opensymphony.module.sitemesh.taglib.decorator.TitleTag.class);
    _jspx_th_dec_005ftitle_005f0.setPageContext(_jspx_page_context);
    _jspx_th_dec_005ftitle_005f0.setParent(null);
    // /decorators/admin.jsp(9,7) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_dec_005ftitle_005f0.setDefault("Admin");
    int _jspx_eval_dec_005ftitle_005f0 = _jspx_th_dec_005ftitle_005f0.doStartTag();
    if (_jspx_th_dec_005ftitle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.reuse(_jspx_th_dec_005ftitle_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.reuse(_jspx_th_dec_005ftitle_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /decorators/admin.jsp(11,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/template/admin/css/bootstrap.min.css");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /decorators/admin.jsp(12,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/template/admin/font-awesome/4.2.0/css/font-awesome.min.css");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /decorators/admin.jsp(15,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/template/admin/fonts/fonts.googleapis.com.css");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /decorators/admin.jsp(18,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/template/admin/css/ace.min.css");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_dec_005fbody_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dec:body
    com.opensymphony.module.sitemesh.taglib.decorator.BodyTag _jspx_th_dec_005fbody_005f0 = (com.opensymphony.module.sitemesh.taglib.decorator.BodyTag) _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.get(com.opensymphony.module.sitemesh.taglib.decorator.BodyTag.class);
    _jspx_th_dec_005fbody_005f0.setPageContext(_jspx_page_context);
    _jspx_th_dec_005fbody_005f0.setParent(null);
    int _jspx_eval_dec_005fbody_005f0 = _jspx_th_dec_005fbody_005f0.doStartTag();
    if (_jspx_th_dec_005fbody_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.reuse(_jspx_th_dec_005fbody_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.reuse(_jspx_th_dec_005fbody_005f0);
    return false;
  }
}
